name: 'DecoratedPotDupe'
version: '${version}'
main: xyz.puppet57.decoratedpotdupe.DecoratedPotDupe
api-version: '1.20'
description: 'Lets you dupe items by breaking a decorated pot with items inside while spamming sneak'
